FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN go build -o email-worker ./worker/main.go

# Final image
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/email-worker /app/email-worker

CMD ["/app/email-worker"]